### ISSUE TITLE
backport/main does not compile against ubuntu kernel 6.8.0-45.45

### ISSUE THREAD

**Issue by lleo19** [intel-gpu/intel-gpu-i915-backports#198] opened 2024-10-18 18:59 UTC
latest release still fails with:

```
/var/lib/dkms/intel-i915-dkms/1.24.5.15.240718.18/build/drivers/gpu/drm/i915/display/intel_dp_mst.c: In function ‘intel_mst_enable_dp’:
/var/lib/dkms/intel-i915-dkms/1.24.5.15.240718.18/build/drivers/gpu/drm/i915/display/intel_dp_mst.c:777:54: error: passing argument 2 of ‘drm_dp_add_payload_part2’ from incompatible pointer type [-Werror=incompatible-pointer-types]
  777 |         drm_dp_add_payload_part2(&intel_dp->mst_mgr, &state->base,
      |                                                      ^~~~~~~~~~~~
      |                                                      |
      |                                                      struct drm_atomic_state *
In file included from /var/lib/dkms/intel-i915-dkms/1.24.5.15.240718.18/build/backport-include/drm/drm_dp_mst_helper.h:27,
                 from /var/lib/dkms/intel-i915-dkms/1.24.5.15.240718.18/build/drivers/gpu/drm/i915/display/intel_display_types.h:38,
                 from /var/lib/dkms/intel-i915-dkms/1.24.5.15.240718.18/build/drivers/gpu/drm/i915/display/intel_dp_mst.c:38:
./include/drm/display/drm_dp_mst_helper.h:854:64: note: expected ‘struct drm_dp_mst_atomic_payload *’ but argument is of type ‘struct drm_atomic_state *’
  854 |                              struct drm_dp_mst_atomic_payload *payload);
      |                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
/var/lib/dkms/intel-i915-dkms/1.24.5.15.240718.18/build/drivers/gpu/drm/i915/display/intel_dp_mst.c:777:9: error: too many arguments to function ‘drm_dp_add_payload_part2’
  777 |         drm_dp_add_payload_part2(&intel_dp->mst_mgr, &state->base,
      |         ^~~~~~~~~~~~~~~~~~~~~~~~
./include/drm/display/drm_dp_mst_helper.h:853:5: note: declared here
  853 | int drm_dp_add_payload_part2(struct drm_dp_mst_topology_mgr *mgr,
      |     ^~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by smuqthya** [comment] 2024-10-22 06:26
We have retried the same tag against 6.8.0-45.45, we could not able to reproduce this issue. Is this custom kernel?
Can you share the full log of dkms once.

**Comment by smuqthya** [comment] 2024-11-05 14:59
@lleo19 can we close if not reproducible

**Comment by smuqthya** [comment] 2024-11-13 04:40
closing for now. if you can reproduce. please provide more details and reopen

**Closed by smuqthya** 2024-11-13 04:40 UTC
